{% set version = "4.2-5-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biomod2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/biomod2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/biomod2/biomod2_{{ version }}.tar.gz
  sha256: 1c4ca427b8d6af54de548023dcbe25c7e9cbea7afb684c58b66f4210af9eb4e5

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-abind
    - r-dplyr
    - r-earth
    - r-foreach
    - r-gbm >=2.1.3
    - r-ggplot2
    - r-maxnet
    - r-mass
    - r-mda
    - r-nnet
    - r-presenceabsence
    - r-proc >=1.15.0
    - r-randomforest
    - r-reshape
    - r-reshape2
    - r-rpart
    - r-sp
    - r-terra >=1.6_33
    - r-xgboost
  run:
    - r-base
    - r-abind
    - r-dplyr
    - r-earth
    - r-foreach
    - r-gbm >=2.1.3
    - r-ggplot2
    - r-maxnet
    - r-mass
    - r-mda
    - r-nnet
    - r-presenceabsence
    - r-proc >=1.15.0
    - r-randomforest
    - r-reshape
    - r-reshape2
    - r-rpart
    - r-sp
    - r-terra >=1.6_33
    - r-xgboost

test:
  commands:
    - $R -e "library('biomod2')"           # [not win]
    - "\"%R%\" -e \"library('biomod2')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=biomod2
  dev_url: https://github.com/biomodhub/biomod2
  license: GPL-3.0-only
  summary: Functions for species distribution modeling, calibration and evaluation, ensemble of models, ensemble forecasting and visualization. The package permits to run consistently up to 10 single models on a presence/absences (resp presences/pseudo-absences) dataset and to combine them in ensemble models and ensemble
    projections. Some bench of other evaluation and visualisation tools are also available within the package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - colineroyaux
